### ISSUE TITLE
PDNSServer string representation

### ISSUE THREAD

**Issue by nzlosh** [outini/python-powerdns#1]
I need to allow users to list and request the server_id by string.

When attempting to cast  PDNSServer object to a string, it is composed of the `<class name>:<server_id>`.

Is there any particular reason why casting to string doesn't return just the `server_id`?

**Comment by outini** [comment]
Hello,

This is a mistake by my side, I reworked all `__repr__` and `__str__` methods. You can now cast a  PDNSServer object to a string and only get the `<server_id>`. I hope this would be what you need.

Have a nice day

**Comment by nzlosh** [comment]
Thank you for the quick fix.
