### ISSUE TITLE
Make a new release so that PR #20 (added support for RRSet Records as dicts) is finally available via PyPI

### ISSUE THREAD

**Issue by 991jo** [outini/python-powerdns#27]
PR #20 was merged 1 day after the last release and is therefore not public yet. Would really appreciate if i could finally use the official package :D

**Comment by 991jo** [comment]
Any progress on this issue? Is there a way to help out?

**Comment by 991jo** [comment]
Hi, this is the weekly reminder that this issue is still open.

**Comment by outini** [comment]
Hello,
The release 2.1.0 is now available on PyPI (https://pypi.org/project/python-powerdns/2.1.0/).
Thank you for the contribution !
