### ISSUE TITLE
Availability on pypi.org

### ISSUE THREAD

**Issue by nzlosh** [outini/python-powerdns#3]
Since the original vente-privée repository no longer exists, will this repository be made available on pypi for python-powerdns module?

**Comment by coolacid** [comment]
An update to this issue would be awesome. :+1:

**Comment by 991jo** [comment]
I am also interested in bringing a recent version of this to pypi. Is there a way I could help?

**Comment by outini** [comment]
Hello,

I will release the version 1.0.0 as soon as possible.
I am dealing with Veepee to get access to the pypi account, this should not take too long (I hope).

In the meantime, the version 1.0.0 is available in the repository.

I keep this issue open to track the release on PYPI.

Sorry for the huge delays of my responses.

**Comment by outini** [comment]
I get back the ownership of this project on pypi, and released the version 1.0.0.

I am closing this issue.
