### ISSUE TITLE
Delete ignores the data field, if more than one record of a given type exists

### ISSUE THREAD

**Issue by marneu** [outini/python-powerdns#5]
If you want to to delete one record where more than one entry of this type exists, all entries of the same type are deleted no matter what data you specify in the RRSet.

Tested with TLSA
``` python
zone.delete_record([
  powerdns.RRSET('_Blah.example.org.', 'TLSA', [('3 1 1 expired key')])
])
```
Deletes all TLSA records for a given name not only the expired one.
In my opinion this is a bug, do you agree?

**Comment by Algirdas-Z** [comment]
I believe this is PowerDNS API limitation, I would suggest first to fetch all records, filter and send full list to "replace"
https://doc.powerdns.com/authoritative/http-api/zone.html#rrset

Otherwise API just removes on everything that matches name and type
```
changetype (string) – MUST be added when updating the RRSet. 
Must be REPLACE or DELETE. With DELETE, all existing RRs matching name and type will be deleted, 
including all comments. 
With REPLACE: when records is present, all existing RRs matching name and type will be deleted, 
and then new records given in records will be created. 
If no records are left, any existing comments will be deleted as well. 
When comments is present, all existing comments for the RRs matching name and type will be deleted, and then new 
comments given in comments will be created.
```

**Comment by outini** [comment]
Hello,

As said by Algirdas-Z, this is a limitation of the powerdns api.

Regards,
