### ISSUE TITLE
AttributError: 'NoneType' object has no attribute 'create_records'

### ISSUE THREAD

**Issue by VGzsysadm** [outini/python-powerdns#6]
Just when call zone.create_records()

Whats wrong ?

**Comment by Algirdas-Z** [comment]
Need more context, but most likely you do not have zone object populated, thus it doesn't have create_records method.

**Comment by outini** [comment]
Hello,

As Algirdas-Z said, it might be an issue when retrieving your zone's content.
Unfortunately, there is nothing to be done at code level in this case without something to reproduce by my side.

Regards,
